language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "pip install --use-mirrors pep8"
  - "pip install --use-mirrors -r test-requirements.txt"
  - "pip install --use-mirrors -r requirements.txt"

script:
  - pep8 --exclude=docs .
  - nosetests --with-coverage --cover-package=streams

notifications:
  email:
    - nineseconds@yandex.ru

matrix:
  allow_failures:
    - python: "3.4"
